#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define RETRO_TAPPING
#define RETRO_TAPPING_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define COMBO_TERM 1000

#pragma once



#endif
